spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
# Login username of the database.
  username: root
# Login password of the database.
  password: Shubh@11
 
# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
 
# DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Defaults to "create-drop" when using an embedded database and no schema manager was detected. Otherwise, defaults to "none".
  jpa:
    hibernate: 
      ddl-auto: update
# Whether to enable logging of SQL statements.
    show-sql: true
 
# Hibernate additional native properties to set on the JPA provider.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: thread
        format_sql: true
 
# Fix Postgres JPA Error (Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented).
        jdbc.lob.non_contextual_creation: true